# Thanks @niess (https://github.com/niess) for python-appimage, creating appimages for Python is easy as pie!!

name: AppImage
on: 
  push:
    paths:
      - 'guiscrcpy/**'
      - '.github/workflows/appimage.yml'
  pull_request:
    paths:
      - 'guiscrcpy/**'
      - '.github/workflows/appimage.yml'

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}

    - name: Test AppImage
      run: |
        python -m pip install python-appimage
        echo $(realpath .) > appimage/requirements.txt
        python -m python_appimage build app appimage \
                                            --linux-tag=manylinux1_x86_64
    
    - name: Extract AppImage
      run: |
        ./guiscrcpy-x86_64.AppImage --appimage-extract
        mv squashfs-root AppDir
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x ./appimagetool-x86_64.AppImage
    
    - name: Download adb
      run: | 
        wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
        unzip platform-tools-latest-linux.zip -d adb
        cp adb/platform-tools/adb AppDir/usr/bin/.
    
    - name: Download scrcpy
      run: |
        wget https://dl.bintray.com/srevinsaju/guiscrcpy/scrcpy/scrcpy
        wget https://dl.bintray.com/srevinsaju/guiscrcpy/scrcpy/scrcpy-server
        mkdir -p AppDir/usr/bin
        cp scrcpy AppDir/usr/bin/.
        chmod +x AppDir/usr/bin/scrcpy
        mkdir -p AppDir/usr/share/scrcpy
        cp scrcpy-server AppDir/usr/share/scrcpy/.

    - name: Patch PyQt5 pass travis
      run: |
        wget https://dl.bintray.com/srevinsaju/guiscrcpy/scrcpy/libxkbcommon.so.0
        wget https://dl.bintray.com/srevinsaju/guiscrcpy/scrcpy/libxkbcommon-x11.so.0.0.0
        cp libxkbcommon.so.0 AppDir/opt/python3.8/lib/python3.8/site-packages/PyQt5/Qt/lib/.
        cp libxkbcommon-x11.so.0.0.0 AppDir/opt/python3.8/lib/python3.8/site-packages/PyQt5/Qt/lib/libxkbcommon-x11.so.0
    - name: Download scrcpy binary deps
      run: |
        wget https://dl.bintray.com/srevinsaju/guiscrcpy/scrcpy/scrcpy_processed.tar.gz
        tar -xf scrcpy_processed.tar.gz
        cp scrcpy_processed/* AppDir/usr/lib/.
    - name: Reimage AppImage
      run: |
        rm ./guiscrcpy-x86_64.AppImage
        ./appimagetool-x86_64.AppImage --comp gzip AppDir -n
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: guiscrcpy-x86_64.AppImage
        path: guiscrcpy-x86_64.AppImage

    
