name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt install libsnappy-dev libsqlite3-dev desktop-file-utils python3-virtualenv python3-venv
          sudo pip3 install virtualenv
          sudo ln -s /usr/lib/python3/dist-packages/virtualenv.py /usr/local/bin/virtualenv
          sudo chmod +x /usr/local/bin/virtualenv
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: get Bundle
        run: |
          git clone https://github.com/AppImage/pkg2appimage.git --depth=1
          cd pkg2appimage
          chmod +x ./pkg2appimage
          ./pkg2appimage ../io.srevinsaju.guiscrcpy.yml
          cd ..
          ls
          
      - name: show dir 
        run: ls
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: guiscrcpy.AppImage
          # Directory containing files to upload
          path: pkg2appimage/out/guiscrcpy-.glibc2.25-x86_64.AppImage
